const ActionTypes =
{
    INITIALIZE:             'INITIALIZE',
    WINDOW_CLICK:           'WINDOW_CLICK',
    HEADER_MENU_SHOW:       'HEADER_MENU_SHOW',

    SIGN_IN:                'SIGN_IN',
    SIGN_OUT:               'SIGN_OUT',
    AUTH_STATE_CHANGED:     'AUTH_STATE_CHANGED',

    ADD_PROJECT:            'ADD_PROJECT',
    CANCEL_ADD_PROJECT:     'CANCEL_ADD_PROJECT',
    SUBMIT_PROJECT:         'SUBMIT_PROJECT',
    DELETE_PROJECT:         'DELETE_PROJECT',
    ON_PROJECTS:            'ON_PROJECTS',
    SELECT_PROJECT:         'SELECT_PROJECT',
    SHOW_PROJECT_SELECTION: 'SHOW_PROJECT_SELECTION',
    HIDE_PROJECT_SELECTION: 'HIDE_PROJECT_SELECTION',
}

export default ActionTypes
